### ISSUE TITLE
Quality but Security

### ISSUE THREAD

**Issue by Klemci** [runeandre/slipstream_windows_updates#1]
Hello,

that's good, all listed until cumulative updates match what i had noted down earlier, today i want to build (based on enterprise x64) an up to date ISO to use in virtual machine..

The cumulative updates have two versions, one big (300mb) called Quality (listed here) and another smaller called Security Only (50mb), that's the ones i want bc Q are big and contain not necessarilly non-critical files... SO are also faster to slisptream and are lighter in the end once installed.

exemple:
KB4534310 (330mb)
is
KB4534314 (50mb)

Would you list those SO alternate too ?

//

Is it an obsolete post Convenient update ?:
KB3179573-X64 / Rollup 2016-8 (2.3mb)

Please.

**Comment by runeandre** [comment]
Sorry for the late reply, didn't notice the message before now.

In short, the list of updates is based on other lists I have found and what I have found to be missing using WSUS (https://download.wsusoffline.net/) when I run it on an updated Windows 7 installation.

I have tried to keep the list as minimal as possible, using cumulative updates for instance.
There might be additonal files on cumulative updates, I have not looked into it.
They are nice as they simplify the list of updates needed.

You can make your own list, and separate them in numbered folders if you need to control the update sequence. 

I couldn't find KB3179573 when I checked the last version now, might have removed it.
